export type DanceStyle = "salsa" | "bachata" | "salsa_bachata" | "other";

export type EventRecord = {
  id: string;
  slug: string;
  titleEs: string;
  titleEn: string;
  descriptionEs: string;
  descriptionEn: string;
  coverImageUrl: string;
  galleryUrls: string[];
  danceStyle: DanceStyle;
  city: string;
  area?: string | null;
  venueName: string;
  address?: string | null;
  startsAt: string;
  endsAt?: string | null;
  priceAmount?: number | null;
  priceText?: string | null;
  currency: string;
  organizerName: string;
  organizerId?: string | null;
  academyId?: string | null;
  contactUrl: string;
  externalUrl?: string | null;
  isFeatured: boolean;
  createdAt?: string;
};

export type LocalizedEvent = {
  id: string;
  slug: string;
  title: string;
  description: string;
  coverImageUrl: string;
  galleryUrls: string[];
  danceStyle: DanceStyle;
  city: string;
  area?: string | null;
  venueName: string;
  address?: string | null;
  startsAt: string;
  endsAt?: string | null;
  priceAmount?: number | null;
  priceText?: string | null;
  currency: string;
  organizerName: string;
  organizerId?: string | null;
  academyId?: string | null;
  contactUrl: string;
  externalUrl?: string | null;
  isFeatured: boolean;
  createdAt?: string;
};
