insert into public.events (
  slug,
  title_es,
  title_en,
  description_es,
  description_en,
  cover_image_url,
  dance_style,
  city,
  area,
  venue_name,
  address,
  starts_at,
  price_amount,
  currency,
  organizer_name,
  contact_url,
  external_url,
  is_featured
)
values
  (
    'salsa-social-zona-10',
    'Salsa Social en Zona 10',
    'Salsa Social in Zona 10',
    'Una noche relajada para bailar salsa y bachata con DJs locales, clases introductorias y ambiente social.',
    'A relaxed night of salsa and bachata with local DJs, intro classes, and a social atmosphere.',
    'https://images.unsplash.com/photo-1515169067868-5387ec356754?auto=format&fit=crop&w=1200&q=80',
    'salsa_bachata',
    'Ciudad de Guatemala',
    'Zona 10',
    'Casa de la Danza',
    'Diagonal 6, Zona 10',
    '2026-03-20T20:00:00-06:00',
    50,
    'GTQ',
    'Explora Salsa GT',
    'https://wa.me/50255550101',
    'https://instagram.com/explorasalsagt',
    true
  ),
  (
    'bachata-sunset-antigua',
    'Bachata Sunset en Antigua',
    'Bachata Sunset in Antigua',
    'Taller corto al atardecer seguido de social bachatero con vista al volcán.',
    'A short sunset workshop followed by a bachata social with a volcano view.',
    'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?auto=format&fit=crop&w=1200&q=80',
    'bachata',
    'Antigua Guatemala',
    'Centro',
    'Terraza Antigua',
    '5a Avenida Norte',
    '2026-03-22T18:30:00-06:00',
    75,
    'GTQ',
    'Bachata Antigua',
    'https://wa.me/50255550102',
    'https://instagram.com/bachataantigua',
    true
  );

insert into public.academies (
  slug,
  name,
  description_es,
  description_en,
  cover_image_url,
  city,
  area,
  address,
  styles_taught,
  whatsapp_url,
  instagram_url,
  website_url,
  is_featured
)
values
  (
    'casa-de-la-danza',
    'Casa de la Danza',
    'Academia con clases regulares de salsa en línea, bachata sensual y práctica social para todos los niveles.',
    'Academy with recurring classes in salsa on1, sensual bachata, and social practice for all levels.',
    'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80',
    'Ciudad de Guatemala',
    'Zona 10',
    'Diagonal 6, Zona 10',
    '{"salsa","bachata"}',
    'https://wa.me/50255550111',
    'https://instagram.com/casadeladanzagt',
    'https://casadeladanza.gt',
    true
  ),
  (
    'ritmo-antigua',
    'Ritmo Antigua',
    'Espacio de aprendizaje con enfoque social, clases para visitantes y comunidad local en Antigua.',
    'Learning space with a social focus, classes for visitors, and a local community in Antigua.',
    'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1200&q=80',
    'Antigua Guatemala',
    'Centro',
    '6a Calle Oriente',
    '{"salsa_bachata","other"}',
    'https://wa.me/50255550112',
    'https://instagram.com/ritmoantigua',
    null,
    true
  );
