import type { ResourceRecord } from "@/types/resource";

const VERIFIED_AT = "2026-08-13T00:00:00-06:00";

export const initialCommunityResources: ResourceRecord[] = [
  {
    id: "tiendanza",
    slug: "tiendanza",
    name: "Tiendanza",
    resourceKind: "business",
    categories: ["dancewear"],
    descriptionEs: "Tienda en línea de zapatos, ropa y accesorios de danza.",
    descriptionEn: "Online shop for dance shoes, clothing, and accessories.",
    countryCode: "GT",
    instagramUrl: "https://www.instagram.com/tiendanza/",
    sourceUrl: "https://www.instagram.com/tiendanza/",
    sourceLabel: "Perfil público de Instagram",
    verificationStatus: "source_confirmed",
    lastVerifiedAt: VERIFIED_AT,
    isFeatured: true,
    isPublished: true,
    sortOrder: 10
  },
  {
    id: "mj-dance-store-gt",
    slug: "mj-dance-store-gt",
    name: "MJ Dance Store",
    resourceKind: "business",
    categories: ["dancewear"],
    descriptionEs: "Zapatos de baile diseñados para ofrecer ligereza, giro y estilo.",
    descriptionEn: "Dance shoes designed for light movement, turns, and style.",
    countryCode: "GT",
    instagramUrl: "https://www.instagram.com/mjdancestoregt/",
    sourceUrl: "https://www.instagram.com/mjdancestoregt/",
    sourceLabel: "Perfil público de Instagram",
    verificationStatus: "source_confirmed",
    lastVerifiedAt: VERIFIED_AT,
    isFeatured: true,
    isPublished: true,
    sortOrder: 20
  },
  {
    id: "jose-medina-dj",
    slug: "jose-medina-dj",
    name: "Jose Medina",
    resourceKind: "professional",
    categories: ["dj"],
    descriptionEs: "DJ y bailarín. También puedes consultar su perfil profesional en SomosSalsa.",
    descriptionEn: "DJ and dancer. You can also view his professional profile on SomosSalsa.",
    countryCode: "GT",
    instagramUrl: "https://www.instagram.com/jmedinasalsa/",
    teacherSlug: "jose-medina",
    sourceUrl: "https://www.instagram.com/jmedinasalsa/",
    sourceLabel: "Perfil público de Instagram",
    verificationStatus: "source_confirmed",
    lastVerifiedAt: VERIFIED_AT,
    isFeatured: true,
    isPublished: true,
    sortOrder: 30
  },
  {
    id: "dj-lux",
    slug: "dj-lux",
    name: "DJ Lux",
    resourceKind: "professional",
    categories: ["dj"],
    descriptionEs: "DJ recomendado por la comunidad salsera.",
    descriptionEn: "DJ recommended by the salsa community.",
    countryCode: "GT",
    instagramUrl: "https://www.instagram.com/robertolux87/",
    sourceUrl: "https://www.instagram.com/robertolux87/",
    sourceLabel: "Recomendación de la comunidad",
    verificationStatus: "unverified",
    isFeatured: false,
    isPublished: true,
    sortOrder: 40
  },
  {
    id: "dj-pakeyro",
    slug: "dj-pakeyro",
    name: "DJ Pake&ro",
    resourceKind: "professional",
    categories: ["dj"],
    descriptionEs: "DJ y bailarín de salsa y bachata recomendado por la comunidad.",
    descriptionEn: "Salsa and bachata dancer and DJ recommended by the community.",
    countryCode: "GT",
    instagramUrl: "https://www.instagram.com/pakeyro/",
    sourceUrl: "https://www.instagram.com/pakeyro/",
    sourceLabel: "Recomendación de la comunidad",
    verificationStatus: "unverified",
    isFeatured: false,
    isPublished: true,
    sortOrder: 50
  },
  {
    id: "pako-perez-foto",
    slug: "pako-perez-foto",
    name: "Pako Perez",
    resourceKind: "professional",
    categories: ["photography"],
    descriptionEs: "Fotógrafo profesional con trabajo relacionado con la comunidad de baile latino.",
    descriptionEn: "Professional photographer whose work includes the Latin dance community.",
    countryCode: "GT",
    instagramUrl: "https://www.instagram.com/pakoperezfoto/",
    sourceUrl: "https://www.instagram.com/pakoperezfoto/",
    sourceLabel: "Perfil público de Instagram",
    verificationStatus: "source_confirmed",
    lastVerifiedAt: VERIFIED_AT,
    isFeatured: true,
    isPublished: true,
    sortOrder: 60
  }
];
